project:
  type: website
  output-dir: ../.

website:
  title: "Gabriel Chua"
  navbar:
    right:
      - blog.qmd
      - text: AI Events
        href: https://lu.ma/sg-ai
      - icon: github
        href: https://github.com/gabrielchua
      - icon: twitter
        href: https://x.com/gabrielchua_
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-chua/
  google-analytics: "G-Q7QTXLJNM3"

format:
  html:
    theme: flatly
    css: styles.css
